#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Aivaras Prudnikovas
title: Aivaras Prudnikovas

# Short bio or description (displayed in the header)
description: Software engineer specializing in web application development. Building enterprise web products, Microservices and Android apps.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars.githubusercontent.com/u/1052642

#
# Flags below are optional
#
external_links:
  - label: 'Email me'
    href: 'mailto:ivar.prudnikov@gmail.com'
  - label: 'Github'
    href: 'https://github.com/ivarprudnikov'
  - label: 'Medium'
    href: 'https://medium.com/@ivarprudnikov'
  - label: 'Linkedin'
    href: 'https://www.linkedin.com/in/ivarprudnikov'
  - label: 'Stackoverflow'
    href: 'http://stackoverflow.com/users/906265/aivaras-prudnikovas'
  - label: 'Instagram'
    href: 'https://instagram.com/ivarprudnikov'
  - label: 'Twitter'
    href: 'https://www.twitter.com/ivarprudnikov'
  - label: 'RSS feed'
    href: 'http://www.ivarprudnikov.com/feed.xml'


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-43884937-2

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://www.ivarprudnikov.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
- jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
- jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
- .idea
